#!/bin/bash

for F in \
        .gitignore \
        Makefile \
        bib \
        bibfile.bib \
        A0706-pt.tex \
        A0706-pt-PRES.tex \
        A0706-pt-HOUT.tex \
        gitter; do
    git add $F && git commit -m "ADD the $F"
done

git push

