#!/bin/bash

RAW="${1}"

#----------------------------------------------------------------------#
#                            Minimum Checks                            #
#----------------------------------------------------------------------#

function error(){
    echo "ERROR: $@" >&2
}

if test -z "${RAW}"; then
    error "Please provide a new directory name argument."
    exit 1
fi

NEW="$(echo $RAW | sed 's/\([0-9]\{2\}-[a-zA-Z]*\).*/\1/g')"

if test "${#NEW}" -lt 4; then
    error 'New dir name MUST be in the format "##-Name", i.e., "[0-9]{2}-[a-zA-Z]*".'
    exit 2
fi

if test -e "${NEW}"; then
    error "${NEW} already exists. Aborting."
    exit 3
fi

#----------------------------------------------------------------------#
#                          Parsed Parameters                           #
#----------------------------------------------------------------------#

CUR="$(basename $(pwd))"
CURNUM="${CUR:0:2}"
CURNAM="${CUR:3}"

NEWNUM="${NEW:0:2}"
NEWNAM="${NEW:3}"

#----------------------------------------------------------------------#
#                               Make New                               #
#----------------------------------------------------------------------#

mkdir "${NEW}"
cd "${NEW}"

tar jxvf ../../../Part-A-Fundamentals/00-Template/00-Template/template.tar.bz2

