#!/bin/bash

# HUGE thanks to Kurt Pfeifle, at https://stackoverflow.com/a/27194202/4038337

IF="${1}"
COLOR="${2:-#dfdfdf}"

if test ! -f "${IF}"; then
    echo "Problem with arguments!"
    echo "Please supply (i) existing input file name."
    exit -1
fi

OF="${IF/.*/}-alpha-${COLOR:1:6}.png"

echo "${IF} --> ${OF}"

convert                        \
    "${IF}"                    \
    \(                         \
       -clone 0                \
       -fill "${COLOR}"        \
       -colorize 100           \
    \)                         \
    \(                         \
       -clone 0,1              \
       -compose difference     \
       -composite              \
       -separate               \
       +channel                \
       -evaluate-sequence max  \
       -auto-level             \
    \)                         \
     -delete 1                 \
     -alpha off                \
     -compose over             \
     -compose copy_opacity     \
     -composite                \
    "${OF}"

